### ISSUE TITLE
Very basic question - how do I "install" it?

### ISSUE THREAD

**Issue by yugawara** [semorrison/lean-category-theory#6]
Hi,

I am new to both LEAN *and* Category theory...  If you see my VS Code screenshot below, you see there are many warnings.   Have I missed some basic configuration (say, setting paths to certain directories, etc) ? 

Cheers,
Yasu, Tokyo

![image](https://cloud.githubusercontent.com/assets/578499/26783200/e60fbe14-4a31-11e7-9c83-09bb68ca0779.png)

**Comment by kim-em** [comment]
Dear Yasu,

the `lean-category-theory` package tracks the master version of `lean`, so you'll need to be running that, rather than the last released version.

The steps are thus:
1. clone and compile Lean
2. install VS Code
3. tell VS Code where to find the Lean executable
4. open the `lean-category-theory` folder in VS Code

For step 1., I use:
````
git clone git@github.com:leanprover/lean.git
cd lean
mkdir -p build/debug
cd build/debug
cmake -DCMAKE_BUILD_TYPE=DEBUG -G Ninja ../../src
ninja
````

For step 3., open settings in VS Code (this opens `settings.json` in the editor) and make sure there is an appropriate configuration line like:
````
    "lean.executablePath": "/Users/scott/bin/lean",
````

You can also build everything at the command line, without setting up VS Code, by typing `leanpkg build` (assuming when you compiled Lean you ensured its executables are on your path; otherwise you need to specify the path for `leanpkg`).

Please let me know if you have further difficulties.

best regards,
Scott

**Comment by yugawara** [comment]
Thank you so much Scott, let me try!

**Comment by yugawara** [comment]
and it has worked - Thank you so much!
